### ISSUE TITLE
class-my-theme-kirki.php

### ISSUE THREAD

**Issue by LebCit** [aristath/kirki-helpers#13]
Hello @aristath 

Just a note, the new class didn't work for me at the beggining.
**I had to put** `require_once get_template_directory() . '/inc/class-my-theme-kirki.php';`
**before** `require get_template_directory() . '/inc/customizer.php';` in the functions.php file
to make the new class works without an error saying that the My_Theme_Kirki was not found.

Have a nice day and thanks a lot for all your efforts.

**Comment by aristath** [comment]
Thanks for the note! I'm sure it will be of use to others too 👍
