### ISSUE TITLE
WP 4.7 and Kirki_Installer_Control

### ISSUE THREAD

**Issue by Anydog** [aristath/kirki-helpers#14]
Hi,
just updated to WP 4.7 in found out that recommended helper method using class [Kirki_Installer_Control ](https://github.com/aristath/kirki-helpers/blob/master/include-kirki.php#L17)doesn't work with WP 4.7.
Any ideas ? Did something change with WP_Customize_Control in this update ?

**Comment by aristath** [comment]
I'll take a look and push any changes required later today 👍 
Thanks for reporting this!

**Comment by Anydog** [comment]
Hi,
it seems (as far as I can tell) that customizer layout has completely changed, and sections and panels are rendering differently ...
Check this : [http://pastebin.com/UuXTfFff](http://pastebin.com/UuXTfFff) - I removed the iframe and added simple button redirecting to TGMPA install plugin, and have two versions - for WP < 4.7 and WP >= 4.7

**Comment by aristath** [comment]
fixed
