### ISSUE TITLE
ThemeCheck Issues

### ISSUE THREAD

**Issue by Vishal-Deshpande** [aristath/kirki-helpers#4]
ThemeCheck is not happy with the following issues in KirKI Helpers. I know its just an "INFO" and not warning so nothing to take that seriously, but iframe is something every wp developer prefers to stay away from.  Can you suggest some quick fix to resolve this issue?
## ThemeCheck Output

INFO: iframe was found in the file include-kirki.php iframes are sometimes used to load unwanted adverts and code on your site.

Line 7: \* A simple control that will render the installer <iframe>.

Line 9: \* as well as style the section & the iframe.

Line 20: iframe#kirki-customizer-installer { margin-left: -15px; height: 158px; }

Line 34: jQuery('iframe#kirki-customizer-installer').load( function() {

Line 35: jQuery('iframe#kirki-customizer-installer').contents().find('head').append( install

**Comment by suganyaselvakumar** [comment]
KirKI Helpers have the following two textdomain.
file path: include-kirki.php (line no:41 and  58 )
the above issue was not satisfied the unit test. Kindly resolve the issue

**Comment by aristath** [comment]
@PlayerThemes I'm currently investigating alternative methods to propose the plugin installation.
The iframe is the simplest method to do it and it doesn't look bad either.
Any ideas on alternative methods?

@suganyaselvakumar these tools are not just copy-paste.
You have to modify them to suit your needs.
If you use them in your own theme, just change the textdomain!
Kindly resolve the issue on your own theme.

**Comment by Vishal-Deshpande** [comment]
@aristath 

Thanks, let me have a look at it.

**Comment by suganyaselvakumar** [comment]
@aristath  thanks , but I already changed the textdomain.

**Comment by aristath** [comment]
Closing this one as we no longer use an iframe
