### ISSUE TITLE
Multisite compatibility

### ISSUE THREAD

**Issue by ragzor** [aristath/kirki-helpers#5]
Hey Aristath!

Is there a way to make this work on a multisite installation?

**Comment by aristath** [comment]
Why does it not run for you on a multisite?
Did you have any issues?

**Comment by ragzor** [comment]
Not sure why yet, however the Iframe is loading the plugins page of the network admin

### On a Multisite

![Image of Multi Site](http://i.imgur.com/oj1bW1M.png)
