### ISSUE TITLE
wp 4.6 and include-kirki.php

### ISSUE THREAD

**Issue by leeb003** [aristath/kirki-helpers#7]
Hello Aristeides,
Thanks for your work on Kirki, I've been using it for the last couple of weeks on a new theme and it's helped a lot with the customizer.
I was testing and just updated my WP to version 4.6 and noticed that the customizer install now button for Kirki generated in the iframe window appears to be blocked now with WP version 4.6, it works with 4.5 just fine.  
I was actually going to switch to the tgmpa route but instead tinkered a bit and basically just cloned that button to the parent window...I'm sure there's a better solution but at least it works again.  Starting at line 36 in include-kirki.php I added...

// Clone button to parent window
var iBody = jQuery('iframe#kirki-customizer-installer').contents().find('body');
var kButton = iBody.find('#plugin_install_from_iframe').clone();
iBody.find('#plugin_install_from_iframe').hide();
parent.jQuery('#customize-control-kirki_installer').append(kButton);

Maybe you are already aware of this but I thought I'd share.

**Comment by aristath** [comment]
Hey there!

I wasn't aware... thank you for bringing this to my attention!

I'll assign to myself and mark this as a bug.
I wanted to investigate alternative implementations anyway, so this is a good opportunity. 👍

**Comment by leeb003** [comment]
I know WordPress made some customizer changes in 4.6, just not sure which change caused that.
Thank you for looking into this Aristeides!

Lee

**Comment by codehaiku** [comment]
Kindly see my pull request here: https://github.com/aristath/kirki-helpers/pull/8

:)

Thanks

**Comment by aristath** [comment]
fixed
